spring.application.name=cagent
spring.mvc.async.request-timeout=600000
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=8000



spring.security.oauth2.client.registration.github.client-id=Ov23lib7cSwpTHiH31uN
spring.security.oauth2.client.registration.github.client-secret=aa0c45cee378d62419958eb7b8168be6919e5767
spring.security.oauth2.client.registration.github.scope=read:user,user:email
