---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	load_code(load_code)
	code_review(code_review)
	security_review(security_review)
	design_review(design_review)
	production_review(production_review)
	final_report(final_report)
	__end__([<p>__end__</p>]):::last
	__start__ --> load_code;
	code_review --> final_report;
	design_review --> final_report;
	load_code --> code_review;
	load_code --> design_review;
	load_code --> production_review;
	load_code --> security_review;
	production_review --> final_report;
	security_review --> final_report;
	final_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
